/* License (MIT)
 * Copyright 2009 Sony Ericsson Mobile Communications AB
 * website: http://developer.sonyericsson.com/
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * Software), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.sonyericsson.web.sdk.view;

import org.jdesktop.application.Action;

import com.sonyericsson.web.sdk.model.AndroidKeys;

public class KeyInfoView extends javax.swing.JFrame {
  private final AndroidKeys androidKeys;
  private final String selectedAlias;

  /** Creates new form keyInfoView */
  public KeyInfoView(AndroidKeys androidKeys, String selectedAlias) {
    initComponents();
    this.androidKeys = androidKeys;
    this.selectedAlias = selectedAlias;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    mainPanel = new javax.swing.JPanel();
    bottomPanel = new javax.swing.JPanel();
    jSeparator1 = new javax.swing.JSeparator();
    buttonPanel = new javax.swing.JPanel();
    cancelButton = new javax.swing.JButton();
    rightButtonPanel = new javax.swing.JPanel();
    saveButton = new javax.swing.JButton();
    middleButtonPanel = new javax.swing.JPanel();
    valuePanel = new javax.swing.JPanel();
    passwordPanel = new javax.swing.JPanel();
    passwordLabel = new javax.swing.JLabel();
    passwordField = new javax.swing.JPasswordField();
    passwordPanel2 = new javax.swing.JPanel();
    passwordLabel2 = new javax.swing.JLabel();
    passwordField2 = new javax.swing.JPasswordField();
    aliasPanel = new javax.swing.JPanel();
    aliasField = new javax.swing.JTextField();
    aliasLabel = new javax.swing.JLabel();
    validityPanel = new javax.swing.JPanel();
    validityField = new javax.swing.JTextField();
    validityLabel = new javax.swing.JLabel();
    namePanel = new javax.swing.JPanel();
    nameField = new javax.swing.JTextField();
    nameLabel = new javax.swing.JLabel();
    organisationPanel = new javax.swing.JPanel();
    organisationField = new javax.swing.JTextField();
    organisationLabel = new javax.swing.JLabel();
    organisationUnitPanel = new javax.swing.JPanel();
    organisationUnitField = new javax.swing.JTextField();
    organisationUnitLabel = new javax.swing.JLabel();
    locationPanel = new javax.swing.JPanel();
    locationField = new javax.swing.JTextField();
    locationLabel = new javax.swing.JLabel();
    StatePanel = new javax.swing.JPanel();
    stateField = new javax.swing.JTextField();
    stateLabel = new javax.swing.JLabel();
    countryPanel = new javax.swing.JPanel();
    countryField = new javax.swing.JTextField();
    countryLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setName("Form"); // NOI18N

    mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
    mainPanel.setName("mainPanel"); // NOI18N
    mainPanel.setLayout(new java.awt.BorderLayout());

    bottomPanel.setName("bottomPanel"); // NOI18N
    bottomPanel.setLayout(new java.awt.BorderLayout());

    jSeparator1.setName("jSeparator1"); // NOI18N
    bottomPanel.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

    buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
    buttonPanel.setName("buttonPanel"); // NOI18N
    buttonPanel.setLayout(new java.awt.BorderLayout());

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.sonyericsson.web.sdk.controller.WebSDK.class).getContext().getResourceMap(KeyInfoView.class);
    cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
    cancelButton.setToolTipText(resourceMap.getString("cancelButton.toolTipText")); // NOI18N
    cancelButton.setName("cancelButton"); // NOI18N
    buttonPanel.add(cancelButton, java.awt.BorderLayout.LINE_START);

    rightButtonPanel.setName("rightButtonPanel"); // NOI18N
    rightButtonPanel.setLayout(new java.awt.BorderLayout());

    javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.sonyericsson.web.sdk.controller.WebSDK.class).getContext().getActionMap(KeyInfoView.class, this);
    saveButton.setAction(actionMap.get("saveKey")); // NOI18N
    saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
    saveButton.setToolTipText(resourceMap.getString("saveButton.toolTipText")); // NOI18N
    saveButton.setName("saveButton"); // NOI18N
    rightButtonPanel.add(saveButton, java.awt.BorderLayout.LINE_END);

    buttonPanel.add(rightButtonPanel, java.awt.BorderLayout.LINE_END);

    middleButtonPanel.setName("middleButtonPanel"); // NOI18N

    javax.swing.GroupLayout middleButtonPanelLayout = new javax.swing.GroupLayout(middleButtonPanel);
    middleButtonPanel.setLayout(middleButtonPanelLayout);
    middleButtonPanelLayout.setHorizontalGroup(
      middleButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 405, Short.MAX_VALUE)
    );
    middleButtonPanelLayout.setVerticalGroup(
      middleButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 23, Short.MAX_VALUE)
    );

    buttonPanel.add(middleButtonPanel, java.awt.BorderLayout.CENTER);

    bottomPanel.add(buttonPanel, java.awt.BorderLayout.PAGE_END);

    mainPanel.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

    valuePanel.setName("valuePanel"); // NOI18N

    passwordPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
    passwordPanel.setName("passwordPanel"); // NOI18N
    passwordPanel.setLayout(new java.awt.BorderLayout(10, 0));

    passwordLabel.setFont(resourceMap.getFont("passwordLabel.font")); // NOI18N
    passwordLabel.setText(resourceMap.getString("passwordLabel.text")); // NOI18N
    passwordLabel.setToolTipText(resourceMap.getString("passwordLabel.toolTipText")); // NOI18N
    passwordLabel.setName("passwordLabel"); // NOI18N
    passwordPanel.add(passwordLabel, java.awt.BorderLayout.PAGE_START);

    passwordField.setText(resourceMap.getString("passwordField.text")); // NOI18N
    passwordField.setName("passwordField"); // NOI18N
    passwordPanel.add(passwordField, java.awt.BorderLayout.PAGE_END);

    passwordPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
    passwordPanel2.setName("passwordPanel2"); // NOI18N
    passwordPanel2.setLayout(new java.awt.BorderLayout(10, 0));

    passwordLabel2.setFont(resourceMap.getFont("passwordLabel2.font")); // NOI18N
    passwordLabel2.setText(resourceMap.getString("passwordLabel2.text")); // NOI18N
    passwordLabel2.setToolTipText(resourceMap.getString("passwordLabel2.toolTipText")); // NOI18N
    passwordLabel2.setName("passwordLabel2"); // NOI18N
    passwordPanel2.add(passwordLabel2, java.awt.BorderLayout.PAGE_START);

    passwordField2.setText(resourceMap.getString("passwordField2.text")); // NOI18N
    passwordField2.setName("passwordField2"); // NOI18N
    passwordPanel2.add(passwordField2, java.awt.BorderLayout.PAGE_END);

    aliasPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
    aliasPanel.setName("aliasPanel"); // NOI18N
    aliasPanel.setLayout(new java.awt.BorderLayout(10, 0));

    aliasField.setText(resourceMap.getString("aliasField.text")); // NOI18N
    aliasField.setAction(actionMap.get("setName")); // NOI18N
    aliasField.setName("aliasField"); // NOI18N
    aliasPanel.add(aliasField, java.awt.BorderLayout.CENTER);

    aliasLabel.setFont(resourceMap.getFont("aliasLabel.font")); // NOI18N
    aliasLabel.setText(resourceMap.getString("aliasLabel.text")); // NOI18N
    aliasLabel.setToolTipText(resourceMap.getString("aliasLabel.toolTipText")); // NOI18N
    aliasLabel.setName("aliasLabel"); // NOI18N
    aliasPanel.add(aliasLabel, java.awt.BorderLayout.PAGE_START);

    validityPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
    validityPanel.setName("validityPanel"); // NOI18N
    validityPanel.setLayout(new java.awt.BorderLayout(10, 0));

    validityField.setText(resourceMap.getString("validityField.text")); // NOI18N
    validityField.setAction(actionMap.get("setName")); // NOI18N
    validityField.setName("validityField"); // NOI18N
    validityPanel.add(validityField, java.awt.BorderLayout.CENTER);

    validityLabel.setFont(resourceMap.getFont("validityLabel.font")); // NOI18N
    validityLabel.setText(resourceMap.getString("validityLabel.text")); // NOI18N
    validityLabel.setToolTipText(resourceMap.getString("validityLabel.toolTipText")); // NOI18N
    validityLabel.setName("validityLabel"); // NOI18N
    validityPanel.add(validityLabel, java.awt.BorderLayout.PAGE_START);

    namePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
    namePanel.setName("namePanel"); // NOI18N
    namePanel.setLayout(new java.awt.BorderLayout(10, 0));

    nameField.setText(resourceMap.getString("nameField.text")); // NOI18N
    nameField.setAction(actionMap.get("setName")); // NOI18N
    nameField.setName("nameField"); // NOI18N
    namePanel.add(nameField, java.awt.BorderLayout.CENTER);

    nameLabel.setFont(resourceMap.getFont("nameLabel.font")); // NOI18N
    nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
    nameLabel.setToolTipText(resourceMap.getString("nameLabel.toolTipText")); // NOI18N
    nameLabel.setName("nameLabel"); // NOI18N
    namePanel.add(nameLabel, java.awt.BorderLayout.PAGE_START);

    organisationPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
    organisationPanel.setName("organisationPanel"); // NOI18N
    organisationPanel.setLayout(new java.awt.BorderLayout(10, 0));

    organisationField.setText(resourceMap.getString("organisationField.text")); // NOI18N
    organisationField.setAction(actionMap.get("setName")); // NOI18N
    organisationField.setName("organisationField"); // NOI18N
    organisationPanel.add(organisationField, java.awt.BorderLayout.CENTER);

    organisationLabel.setFont(resourceMap.getFont("organisationLabel.font")); // NOI18N
    organisationLabel.setText(resourceMap.getString("organisationLabel.text")); // NOI18N
    organisationLabel.setToolTipText(resourceMap.getString("organisationLabel.toolTipText")); // NOI18N
    organisationLabel.setName("organisationLabel"); // NOI18N
    organisationPanel.add(organisationLabel, java.awt.BorderLayout.PAGE_START);

    organisationUnitPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
    organisationUnitPanel.setName("organisationUnitPanel"); // NOI18N
    organisationUnitPanel.setLayout(new java.awt.BorderLayout(10, 0));

    organisationUnitField.setText(resourceMap.getString("organisationUnitField.text")); // NOI18N
    organisationUnitField.setAction(actionMap.get("setName")); // NOI18N
    organisationUnitField.setName("organisationUnitField"); // NOI18N
    organisationUnitPanel.add(organisationUnitField, java.awt.BorderLayout.CENTER);

    organisationUnitLabel.setFont(resourceMap.getFont("organisationUnitLabel.font")); // NOI18N
    organisationUnitLabel.setText(resourceMap.getString("organisationUnitLabel.text")); // NOI18N
    organisationUnitLabel.setToolTipText(resourceMap.getString("organisationUnitLabel.toolTipText")); // NOI18N
    organisationUnitLabel.setName("organisationUnitLabel"); // NOI18N
    organisationUnitPanel.add(organisationUnitLabel, java.awt.BorderLayout.PAGE_START);

    locationPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
    locationPanel.setName("locationPanel"); // NOI18N
    locationPanel.setLayout(new java.awt.BorderLayout(10, 0));

    locationField.setText(resourceMap.getString("locationField.text")); // NOI18N
    locationField.setAction(actionMap.get("setName")); // NOI18N
    locationField.setName("locationField"); // NOI18N
    locationPanel.add(locationField, java.awt.BorderLayout.CENTER);

    locationLabel.setFont(resourceMap.getFont("locationLabel.font")); // NOI18N
    locationLabel.setText(resourceMap.getString("locationLabel.text")); // NOI18N
    locationLabel.setToolTipText(resourceMap.getString("locationLabel.toolTipText")); // NOI18N
    locationLabel.setName("locationLabel"); // NOI18N
    locationPanel.add(locationLabel, java.awt.BorderLayout.PAGE_START);

    StatePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
    StatePanel.setName("StatePanel"); // NOI18N
    StatePanel.setLayout(new java.awt.BorderLayout(10, 0));

    stateField.setText(resourceMap.getString("stateField.text")); // NOI18N
    stateField.setAction(actionMap.get("setName")); // NOI18N
    stateField.setName("stateField"); // NOI18N
    stateField.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        stateFieldKeyReleased(evt);
      }
    });
    StatePanel.add(stateField, java.awt.BorderLayout.CENTER);

    stateLabel.setFont(resourceMap.getFont("stateLabel.font")); // NOI18N
    stateLabel.setText(resourceMap.getString("stateLabel.text")); // NOI18N
    stateLabel.setToolTipText(resourceMap.getString("stateLabel.toolTipText")); // NOI18N
    stateLabel.setName("stateLabel"); // NOI18N
    StatePanel.add(stateLabel, java.awt.BorderLayout.PAGE_START);

    countryPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
    countryPanel.setName("countryPanel"); // NOI18N
    countryPanel.setLayout(new java.awt.BorderLayout(10, 0));

    countryField.setText(resourceMap.getString("countryField.text")); // NOI18N
    countryField.setAction(actionMap.get("setName")); // NOI18N
    countryField.setName("countryField"); // NOI18N
    countryField.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        countryFieldKeyReleased(evt);
      }
    });
    countryPanel.add(countryField, java.awt.BorderLayout.CENTER);

    countryLabel.setFont(resourceMap.getFont("countryLabel.font")); // NOI18N
    countryLabel.setText(resourceMap.getString("countryLabel.text")); // NOI18N
    countryLabel.setToolTipText(resourceMap.getString("countryLabel.toolTipText")); // NOI18N
    countryLabel.setName("countryLabel"); // NOI18N
    countryPanel.add(countryLabel, java.awt.BorderLayout.PAGE_START);

    javax.swing.GroupLayout valuePanelLayout = new javax.swing.GroupLayout(valuePanel);
    valuePanel.setLayout(valuePanelLayout);
    valuePanelLayout.setHorizontalGroup(
      valuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(aliasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
      .addComponent(passwordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
      .addComponent(passwordPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
      .addComponent(validityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
      .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
      .addComponent(organisationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, valuePanelLayout.createSequentialGroup()
        .addComponent(StatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(countryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addComponent(locationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
      .addComponent(organisationUnitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
    );
    valuePanelLayout.setVerticalGroup(
      valuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(valuePanelLayout.createSequentialGroup()
        .addComponent(aliasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(passwordPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(validityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(organisationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(organisationUnitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(locationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(valuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(countryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(StatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    mainPanel.add(valuePanel, java.awt.BorderLayout.CENTER);

    getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void stateFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateFieldKeyReleased
      // TODO add your handling code here:
    }//GEN-LAST:event_stateFieldKeyReleased

    private void countryFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryFieldKeyReleased
      // TODO add your handling code here:
    }//GEN-LAST:event_countryFieldKeyReleased

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel StatePanel;
  private javax.swing.JTextField aliasField;
  private javax.swing.JLabel aliasLabel;
  private javax.swing.JPanel aliasPanel;
  private javax.swing.JPanel bottomPanel;
  private javax.swing.JPanel buttonPanel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JTextField countryField;
  private javax.swing.JLabel countryLabel;
  private javax.swing.JPanel countryPanel;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JTextField locationField;
  private javax.swing.JLabel locationLabel;
  private javax.swing.JPanel locationPanel;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JPanel middleButtonPanel;
  private javax.swing.JTextField nameField;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JPanel namePanel;
  private javax.swing.JTextField organisationField;
  private javax.swing.JLabel organisationLabel;
  private javax.swing.JPanel organisationPanel;
  private javax.swing.JTextField organisationUnitField;
  private javax.swing.JLabel organisationUnitLabel;
  private javax.swing.JPanel organisationUnitPanel;
  private javax.swing.JPasswordField passwordField;
  private javax.swing.JPasswordField passwordField2;
  private javax.swing.JLabel passwordLabel;
  private javax.swing.JLabel passwordLabel2;
  private javax.swing.JPanel passwordPanel;
  private javax.swing.JPanel passwordPanel2;
  private javax.swing.JPanel rightButtonPanel;
  private javax.swing.JButton saveButton;
  private javax.swing.JTextField stateField;
  private javax.swing.JLabel stateLabel;
  private javax.swing.JTextField validityField;
  private javax.swing.JLabel validityLabel;
  private javax.swing.JPanel validityPanel;
  private javax.swing.JPanel valuePanel;
  // End of variables declaration//GEN-END:variables

  public String getAlias() {
    return aliasField.getText();
  }

  public String getPassword() {
    return passwordField.getText();
  }

  public int getValidity() {
    return Integer.parseInt(validityField.getText());
  }

  public String getOrganisation() {
    return organisationField.getText();
  }

  public String getOrganisationUnit() {
    return organisationUnitField.getText();
  }

  public String getCountry() {
    return countryField.getText();
  }

  public String getLocationInfo() {
    return locationField.getText();
  }

  public String getStateInfo() {
    return stateField.getText();
  }

  @Action
  public void saveKey() {
    androidKeys.createKey(aliasField.getText(), passwordField.getText(), 10000, null, null, null, null, null, null);
  }
}
