/* License (MIT)
 * Copyright 2009 Sony Ericsson Mobile Communications AB
 * website: http://developer.sonyericsson.com/
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * Software), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.sonyericsson.web.sdk.view;

import com.sonyericsson.web.sdk.view.dialog.DialogListener;
import com.sun.awt.AWTUtilities;
import java.awt.Component;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.jdesktop.application.Action;

public class PromptDialog extends JDialog {
  private DialogListener listener;

  /** Creates new form PromptDialog */
  public PromptDialog(JFrame parent, String title, String information, String value, boolean password) {
    super(parent, true);
    init(information, value, parent);
  }

  /** Creates new form PromptDialog */
  public PromptDialog(JDialog parent, String title, String information, String value, boolean password) {
    super(parent, true);
    init(information, value, parent);
  }

  private void init(String information, String value, Component parent) {
    setUndecorated(true);
    try {
      AWTUtilities.setWindowOpaque(this, false);
    } catch (Throwable t) {
    }
    initComponents();
    titleLabel.setText(information);
    valueTextField.setText(value);
    setLocation(parent.getX() + (parent.getWidth() - getWidth()) / 2, parent.getY() + (parent.getHeight() - getHeight()) / 2);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    roundedRectanglePanel1 = new com.sonyericsson.web.sdk.view.panel.RoundedRectanglePanel();
    jPanel1 = new javax.swing.JPanel();
    titleLabel = new javax.swing.JLabel();
    valueTextField = new javax.swing.JPasswordField();
    jPanel2 = new javax.swing.JPanel();
    cancelButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();

    setName("Form"); // NOI18N

    roundedRectanglePanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
    roundedRectanglePanel1.setMinimumSize(new java.awt.Dimension(300, 130));
    roundedRectanglePanel1.setName("roundedRectanglePanel1"); // NOI18N
    roundedRectanglePanel1.setPreferredSize(new java.awt.Dimension(300, 130));
    roundedRectanglePanel1.setLayout(new java.awt.BorderLayout());

    jPanel1.setName("jPanel1"); // NOI18N
    jPanel1.setOpaque(false);
    jPanel1.setLayout(new java.awt.BorderLayout());

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.sonyericsson.web.sdk.controller.WebSDK.class).getContext().getResourceMap(PromptDialog.class);
    titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
    titleLabel.setName("titleLabel"); // NOI18N
    jPanel1.add(titleLabel, java.awt.BorderLayout.PAGE_START);

    valueTextField.setText(resourceMap.getString("valueTextField.text")); // NOI18N
    valueTextField.setName("valueTextField"); // NOI18N
    jPanel1.add(valueTextField, java.awt.BorderLayout.CENTER);

    roundedRectanglePanel1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

    jPanel2.setName("jPanel2"); // NOI18N
    jPanel2.setOpaque(false);
    jPanel2.setLayout(new java.awt.BorderLayout());

    javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.sonyericsson.web.sdk.controller.WebSDK.class).getContext().getActionMap(PromptDialog.class, this);
    cancelButton.setAction(actionMap.get("Cancel")); // NOI18N
    cancelButton.setIcon(resourceMap.getIcon("cancelButton.icon")); // NOI18N
    cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
    cancelButton.setBorder(null);
    cancelButton.setBorderPainted(false);
    cancelButton.setContentAreaFilled(false);
    cancelButton.setFocusPainted(false);
    cancelButton.setName("cancelButton"); // NOI18N
    cancelButton.setPressedIcon(resourceMap.getIcon("cancelButton.pressedIcon")); // NOI18N
    cancelButton.setRolloverIcon(resourceMap.getIcon("cancelButton.rolloverIcon")); // NOI18N
    jPanel2.add(cancelButton, java.awt.BorderLayout.LINE_START);

    okButton.setAction(actionMap.get("Ok")); // NOI18N
    okButton.setIcon(resourceMap.getIcon("okButton.icon")); // NOI18N
    okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
    okButton.setBorder(null);
    okButton.setBorderPainted(false);
    okButton.setContentAreaFilled(false);
    okButton.setFocusPainted(false);
    okButton.setName("okButton"); // NOI18N
    okButton.setPressedIcon(resourceMap.getIcon("okButton.pressedIcon")); // NOI18N
    okButton.setRolloverIcon(resourceMap.getIcon("okButton.rolloverIcon")); // NOI18N
    jPanel2.add(okButton, java.awt.BorderLayout.LINE_END);

    roundedRectanglePanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

    getContentPane().add(roundedRectanglePanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JButton okButton;
  private com.sonyericsson.web.sdk.view.panel.RoundedRectanglePanel roundedRectanglePanel1;
  private javax.swing.JLabel titleLabel;
  private javax.swing.JPasswordField valueTextField;
  // End of variables declaration//GEN-END:variables


  public void setDialogListener(DialogListener listener) {
    this.listener = listener;
  }

  @Action
  public void Ok() {
    setVisible(false);
    if (listener != null) {
      listener.ok();
    }
  }

  @Action
  public void Cancel() {
    valueTextField.setText("");
    setVisible(false);
    if (listener != null) {
      listener.cancel();
    }
  }

  public String getValue() {
    return new String(valueTextField.getPassword());
  }
}
